language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"
- "./gradlew assembleRelease"

after_success:
- sudo apt-get update
- sudo apt-get install mailutils
- echo "Hello world" | mail -s "Hello from Travis" arshad.ali.sayed.15@gmail.com
- echo "apk of the app is attached" | mail -s "apk of app" -A /home/travis/build/arshadalis/intro_android_demo/app/build/outputs/apk/release/app-release-unsigned.apk arshad.ali.sayed.15@gmail.com
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
