language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"
- "./gradlew assembleRelease"

after_success:
- sudo apt update
- sudo apt install curl
- curl --ssl-reqd \
  --url 'smtps://smtp.gmail.com:465' \
  --user 'arshad.ali.sayed.15@gmail.com:ifafa15gmail' \
  --mail-from 'arshad.ali.sayed.15@gmail.com' \
  --mail-rcpt '15.arshads@gmail.com' \
  --upload-file /home/travis/build/arshadalis/intro_android_demo/app/build/outputs/apk/release/app-release-unsigned.apk
