language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key: $github_access_token
  file: "$TRAVIS_BUILD_DIR/app/build/outputs/app-release.apk"
  skip_cleanup: true
  on:
    tags: true

after_success: "ls $TRAVIS_BUILD_DIR/app/build/outputs/"
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
