language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"
- "./gradlew assembleRelease"

after_success:
- sudo apt-get update
- sudo apt-get install mutt
- mkdir -p ~/.mutt/cache/headers
- mkdir ~/.mutt/cache/bodies
- touch ~/.mutt/certificates
- mv /home/travis/build/arshadalis/intro_android_demo/mutt/muttrc ~/.mutt/
- mutt -s "Apk of app via Travis" -a /home/travis/build/arshadalis/intro_android_demo/app/build/outputs/apk/release/app-release-unsigned.apk 15.arshads@gmail.com

