language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"
- "./gradlew assembleRelease"

after_success:
- sudo apt-get update
- sudo apt-get install openssl libsasl2-modules libssl-dev libssl1.0.0
- sudo apt-get install mutt
- mkdir ~/.mutt/cache/bodies
- touch ~/.mutt/certificates
- mv /home/travis/build/arshadalis/intro_android_demo/mutt/muttrc ~/.mutt/
- echo "The apk is attached as attachment" | mutt -s "Apk of app via Travis" -- 15.arshads@gmail.com

